version: '3.8'

services:
  # Frontend service with TypeScript
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # Exclude the dist folder from the volume mount to avoid build conflicts
      - /app/dist
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - NODE_ENV=development
    # Make sure the container restarts if it crashes
    restart: unless-stopped

  # Backend service (includes API)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/sesa
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped

  # Database service
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This line maps your init.sql to the initialization directory
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sesa
    restart: unless-stopped

volumes:
  postgres_data: